#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

NAME=smsforward
PROG=/usr/bin/smsforward

start_service() {
	config_load "$NAME"

	local enable
	config_get enable settings enable
	[ "$enable" = "1" ] || { echo "Instance \"$NAME\" disabled."; return 1; }

	procd_open_instance
	procd_set_param command /bin/sh -c "rm -f /tmp/smsforward.lock; exec '$PROG'"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-0}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	rm -f /tmp/smsforward.lock
	rm -f /var/run/$NAME.pid
}
